-- Table: public.Users

-- DROP TABLE IF EXISTS public."Users";

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 2147483647),
    "Name" text COLLATE pg_catalog."default",
    "Login" text COLLATE pg_catalog."default",
    "Password" text COLLATE pg_catalog."default",
    "Barrels" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Users"
    OWNER to postgres;



-- Table: public.Fields

-- DROP TABLE IF EXISTS public."Fields";

CREATE TABLE IF NOT EXISTS public."Fields"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 2147483647),
    "Multiplier" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Fields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Fields_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Fields"
    OWNER to postgres;
-- Index: IX_Fields_UserId

-- DROP INDEX IF EXISTS public."IX_Fields_UserId";

CREATE INDEX IF NOT EXISTS "IX_Fields_UserId"
    ON public."Fields" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.OilPumps

-- DROP TABLE IF EXISTS public."OilPumps";

CREATE TABLE IF NOT EXISTS public."OilPumps"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 2147483647),
    "NextPumping" timestamp with time zone NOT NULL,
    "FieldId" integer NOT NULL,
    CONSTRAINT "PK_OilPumps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OilPumps_Fields_FieldId" FOREIGN KEY ("FieldId")
        REFERENCES public."Fields" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."OilPumps"
    OWNER to postgres;
-- Index: IX_OilPumps_FieldId

-- DROP INDEX IF EXISTS public."IX_OilPumps_FieldId";

CREATE INDEX IF NOT EXISTS "IX_OilPumps_FieldId"
    ON public."OilPumps" USING btree
    ("FieldId" ASC NULLS LAST)
    TABLESPACE pg_default;
	
	
INSERT INTO public."Users"(
	"Id", "Name", "Login", "Password", "Barrels")
VALUES 
	(1, 'Нефтяник Василий', 'vasil', 'TXvkIvTwAkOlf0z9DmMSi5of4LsGk8XdtNKg7sSYt5Q=DwC06O3oIQSmbcTjGROkgVCGh1SY', 100),
	(2, 'Чернозолотой магнат', 'magnat', 'LPWCorQonbIL4cTBMokHud+HZxeiPNYy0RUN38n+JXE=NNdS1Ouit8KQgN3g14dlLtMi5VYO', 100),
	(3, 'Oil one love <3', 'oillove', 'NEcuTLnLwOfGMJZiYe1U9j4dvYl2vYw2vwnBIrPmABU=PycrDcC22bqNsuruIf0t0Yk9saXd', 100);
	
INSERT INTO public."Fields"(
	"Id", "Multiplier", "UserId")
VALUES 
	(1, 1, 1),
	(2, 1, 2),
	(3, 1, 3);
	
INSERT INTO public."OilPumps"(
	"Id", "NextPumping", "FieldId")
VALUES 
	(1, NOW(), 1),
	(2, NOW(), 2),
	(3, NOW(), 3);
